version: '3'
services:

  kanban-app:
    build: ./kanban-app
    container_name: kanban-app
    environment:
      - DB_SERVER=bigeye.c2u25yrtsbtc.us-west-2.rds.amazonaws.com
      - POSTGRES_DB=bigeye
      - POSTGRES_USER=bigeye
      - POSTGRES_PASSWORD=RlezuOwvOgsGLinw
    ports:
      - 8080:8080

  kanban-ui:
    build: ./kanban-ui
    container_name: kanban-ui
    environment:
      - API_HOST=kanban-app
      - API_PORT=8080
    ports:
      - 4200:80
    links:
      - kanban-app
